language: cpp

before_install:
  - sudo add-apt-repository -y ppa:saiarcot895/chromium-beta
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update

install:
  - sudo apt-get install ninja-build
  - sudo apt-get install cmake

script:
  - cmake -Bbuild -H. -G Ninja && ninja -C build all -v
