set(ENV{TERM} "xterm-color")
execute_process( COMMAND ${TEST} ${ARGS} TIMEOUT 10 RESULT_VARIABLE RESULT_CODE OUTPUT_VARIABLE RESULT_OUTPUT ERROR_VARIABLE RESULT_OUTPUT )
message( "${RESULT_OUTPUT}" )
file( WRITE ${RESULT_FILE} ${RESULT_OUTPUT} )
#if ( NOT RESULT_CODE EQUAL 0 )
#  file( REMOVE ${TEST} )
#endif()

# get_cmake_property(_variableNames VARIABLES)
# foreach (_variableName ${_variableNames})
#  message(STATUS "${_variableName}=${${_variableName}}")
# endforeach()
